### PR TITLE
Polyad colors

### PR DESCRIPTION
**Pull request by jpwesterhof**
- Adds functionality to not only get triad and tetrad colors from a color
  but also n-ad colors using n as an argument. n = 3: triad, n = 4:
  tetrad, n = 5 pentad, etc...
- Added more convenience functions like the existing triad and tetrad.

### CODE REVIEW

**Comment by jpwesterhof** [comment]
I was a bit messy with my first two commits, because I copy pasted it from code I currently use. Hence the two follow up commits with fixes to these two forgotten characters (, and ;).

**Comment by bgrins** [comment]
Alright, sounds good.  I'd rather only export triad and tetrad (and not export all the others), but then expose the new one that allows a variable number of outputs.  I believe we could call it 'polyad', which is what I could find as the name for these groupings: https://en.wiktionary.org/wiki/polyad

**Comment by jpwesterhof** [comment]
Done

**Comment by jpwesterhof** [comment]
Forgot about the internals... done

**Comment by TepigMC** [comment]
This sounds like a cool idea. These need to pass `arguments` to `_applyCombination` like the other public methods. So, just make the private `triad` and `tetrad` functions call `polyad` with `3` or `4` as `n`.

```js
triad: function() {
    return this._applyCombination(triad, arguments);
},
tetrad: function() {
    return this._applyCombination(tetrad, arguments);
},
polyad: function() {
    return this._applyCombination(polyad, arguments);
}

...

function triad(color) {
    return polyad(color, 3);
}

function tetrad(color) {
    return polyad(color, 4);
}
```

**Comment by bgrins** [comment]
Landed this in #250. Thanks @jpwesterhof and sorry for dropping this

**Pull request closed without merging**
