### PR TITLE
Updated and minified jQuery to v3.3.1.min.js (fix for #195)

### PR DESCRIPTION
**Pull request by eloarr**
Fixes issue #195 
Passes retirejs scan (version 2.0.2).

### CODE REVIEW

**Comment by vlaraort** [comment]
I am really waiting this, but it's the project still maintained? there is no commits to master since 2017

**Comment by kowalk** [comment]
@bgrins bump

**Comment by kowalk** [comment]
@bgrins anybody here?

**Comment by vlaraort** [comment]
Still no news?

**Comment by eloarr** [comment]
Alas, none.

**Comment by RB-Develop** [comment]
I'm also in need of this fix. Hope it goes through.

**Comment by xiel** [comment]
I was getting vulnerability alerts for the included outdated jQuery version as well in WhiteSource.

Because the maintainer is not responding for a while, I published a version without jQuery, demo & test folder:
https://www.npmjs.com/package/tinycolor2-without-jquery
https://unpkg.com/browse/tinycolor2-without-jquery@1.4.1/

You can make yarn pick it up instead of the original by using resolutions in your package.json:
```json
"resolutions": {
  "tinycolor2": "https://registry.npmjs.org/tinycolor2-without-jquery/-/tinycolor2-without-jquery-1.4.1.tgz"
}
```

Cheers,
– Felix

**Comment by bgrins** [comment]
Sorry for missing this - I went ahead and removed the jquery dependency on the demo in https://github.com/bgrins/TinyColor/commit/250a1e2421242b336770d50c2b5e1eae292bc727.

**Comment by takwas** [comment]
@bgrins: Thank you for making the [fix](https://github.com/bgrins/TinyColor/commit/250a1e2421242b336770d50c2b5e1eae292bc727). Howbeit, could confirm whether you intend upon making a release of this latest version to [npm](https://www.npmjs.com/package/tinycolor2) soon?

**Comment by bgrins** [comment]
> @bgrins: Thank you for making the fix. Howbeit, could confirm whether you intend upon making a release of this latest version to npm soon?

It shouldn't need a release since the main script file hasn't been touched. jQuery has never been used with the library - only the demo HTML page.

**Comment by xiel** [comment]
@bgrins the problem is, your package includes jQuery **also on npm**. This is what security scans pick up on, see:
https://unpkg.com/browse/tinycolor2@1.4.1/demo/

so yes, a republish with a patch version is very much needed.

**Comment by takwas** [comment]
@xiel: You beat me to it. That's my point exactly.

**Comment by bgrins** [comment]
OK, thank you both for the heads up. Let me see about restricting what gets published to npm and get a new version up.

**Comment by bgrins** [comment]
Alright, 1.4.2 has been published: https://www.npmjs.com/package/tinycolor2/v/1.4.2

**Comment by takwas** [comment]
Awesome stuff! Thank you.

**Pull request closed without merging**
