### PR TITLE
Made code formatting more consistent

### PR DESCRIPTION
**Pull request by andrewarchi**
I have made the formatting of tinycolor.js more consistent. No functionality changes were made, so this shouldn't affect anything other than code cleanliness.
- All the double quotes used for strings `"` were changed to single quotes `'`. Before, both types were used inconsistently.
- All objects are padded with spaces: `{ h: h, s: s, l: l }` as opposed to `{h:h, s:s, l:l}`, `{ h:h, s:s, l:l }`, or even `{ h: h, s: s, l: l}`.
- All operators `+ - * / === =` etc. have spaces around them. Before, this was inconsistent.
- All comments have a space before the text `// Hello World`. Before, a few didn't.

### CODE REVIEW

**Comment by bgrins** [comment]
Hi, thanks sending over the PR.  I'm OK with pretty much all of this, except I'd rather standardize on double quotes so there's less churn

**Comment by TepigMC** [comment]
I personally use single quotes and most places use single quotes as the standard for js, but if you prefer double quotes, I'll change those back.

**Comment by TepigMC** [comment]
I've done some more changes. Here is the complete list. None of this changes functionality at all, so this shouldn't affect anything other than code cleanliness. When ever I made a change, I looked in other occurrences to find the most common or standard way, then chose that.

All Files
- All the strings use double quotes except when there are double quotes nested inside. Before, double quotes were the dominant type.
- A new line was added to the end if it was missing

JavaScript
- Objects are padded with spaces. `{ h: h, s: s, l: l }`
- Object keys have no quotes unless required. `{ "hex": "#FFFFFF" }` becomes `{ hex: "#FFFFFF" }`
- Operators `+ - * / === = !==` etc. have spaces around them.
- Commas and colons have a space after
- Comments have a space before the text `// Hello World` and start capitalized unless it is mid-sentence or a variable name or string.

HTML
- Indentation before was extremely inconsistent. It had some tabs, some spaces, and many of the spaces weren't even multiples of 2 or 4. Now the indentation is multiples of 4.

README.md
- Long lines are wrapped at sentence ends.
- Multi-line code blocks and headers have newlines above and below

**Comment by ryancoughlin** [comment]
Bump on this - +1 for these changes.

**Pull request closed without merging**
