### PR TITLE
Adding Minified file

### PR DESCRIPTION
**Pull request by abishekrsrikaanth**
Adding Minified file

### CODE REVIEW

**Comment by bgrins** [comment]
Hi, thanks for sending over the PR.  Unfortunately, I don't want to keep a minified file up to date with versions (I used to have one but it became out of date).  I now have a build task that minifies it, but I haven't distributed it in the repo since I think many people use their own build systems.

**Comment by abishekrsrikaanth** [comment]
@bgrins, I am trying to set this library up on jsdelivr https://github.com/jsdelivr/jsdelivr/pull/6372 and they wanted to know if we could have a minified file for this library that gets automatically setup everytime you make a release. Both the non-minified and the minified version of the library will automatically be available on jsdelivr.

**Comment by bgrins** [comment]
I guess I could expose `dist/tinycolor-min.js` which is currently in the .gitignore file

**Comment by bgrins** [comment]
Alright, here it is: https://github.com/bgrins/TinyColor/commit/09cbe5492b5a9d7cb7506534a5fc8caec2cebc04.  Do you need a new tag released for this?

**Comment by abishekrsrikaanth** [comment]
Thnx. Yes. I will need a tagged version of the same

**Comment by bgrins** [comment]
> Thnx. Yes. I will need a tagged version of the same

OK 1.2.1 has been tagged: https://github.com/bgrins/TinyColor/tree/1.2.1

**Pull request closed without merging**
